import pandas as pd
from datetime import datetime

# Read the CSV file
df = pd.read_csv('orders.csv')

# Convert order_date to datetime
df['order_date'] = pd.to_datetime(df['order_date'])

# Compute the total revenue generated by the online store for each month
df['month'] = df['order_date'].dt.to_period('M')
monthly_revenue = df.groupby('month').apply(lambda x: (x['product_price'] * x['quantity']).sum())

# Compute the total revenue generated by each product
product_revenue = df.groupby('product_name').apply(lambda x: (x['product_price'] * x['quantity']).sum())

# Compute the total revenue generated by each customer
customer_revenue = df.groupby('customer_id').apply(lambda x: (x['product_price'] * x['quantity']).sum())

# Identify the top 10 customers by revenue generated
top_customers = customer_revenue.nlargest(10)

# Display the results
print("Monthly Revenue:\n", monthly_revenue)
print("\nProduct Revenue:\n", product_revenue)
print("\nCustomer Revenue:\n", customer_revenue)
print("\nTop 10 Customers:\n", top_customers)
